app:
  name: sql-injection

server:
  port: 8181

logging:
  level:
    root: INFO
    com.securecoding.demo: INFO

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: injection
    password: injection
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      schema-locations: classpath:init-schema.sql
      enabled: true
      data-locations: classpath:init-data.sql
      platform: oracle