version: '3.8'
services:
  oracle-db:
    ports:
      - '1521:1521'
    container_name: oracle
    image: gvenzl/oracle-free
    environment:
      ORACLE_PASSWORD: Sup3rS3cr3t0
    networks:
      - app-network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d


  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blasillo/sql-injection:latest
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521:FREE
#      SPRING_DATASOURCE_USERNAME: injection
#      SPRING_DATASOURCE_PASSWORD: injection
    depends_on:
      - oracle-db
    restart: always
    command: sh -c "sleep 20 && java -jar /app/sqli.jar"

    networks:
      - app-network


networks:
  app-network:
    driver: bridge
