version: '3.8'
services:
  oracle-db:
    ports:
      - '1521:1521'
    container_name: oracle
    image: gvenzl/oracle-free
    environment:
      ORACLE_PASSWORD: Sup3rS3cr3t0
    networks:
      - app-network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d


#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8181:8181"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    depends_on:
#      - oracle-db
#    networks:
#      - app-network


networks:
  app-network:
    driver: bridge
